# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build'
on:
  - workflow_dispatch
jobs:
  test:
    uses: ./.github/workflows/main.yml
    with:
      mode: '["build"]'
