# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Test All Configs'
on:
  - workflow_dispatch
jobs:
  build:
    if: github.repository_owner == 'manna-harbour'
    uses: ./.github/workflows/main.yml
    with:
      mode: '["build"]'
      rgb: '[
        "default",
        "LED",
        "PEG",
        "RGB",
      ]'
      alphas: '[
        "default",
        "azerty",
        "beakl15",
        "colemak",
        "colemakdhk",
        "dvorak",
        "halmak",
        "workman",
        "qwerty",
        "qwertz",
        "workman"
      ]'
      nav: '[
        "default",
        "invertedt"
        "vi"
      ]'
      clipboard: '[
        "default",
        "fun",
        "mac",
        "win"
      ]'
      layers: '[
        "default",
        "flip"
      ]'
